<Project Sdk="Microsoft.NET.Sdk">
	<!-- Summoning: greater summons, summoner sacrifice and summon links. -->
	<Import Project="../WrathMod.props" />
	<ItemGroup>
		<ProjectReference Include="../ACHomebrew.Logic/ACHomebrew.Logic.csproj" />
		<ProjectReference Include="../ACHomebrew.Core/ACHomebrew.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="AttributeFeats" />
	</ItemGroup>
</Project>
