<Project Sdk="Microsoft.NET.Sdk">
	<!-- Spell tags and spell-slot arcana. -->
	<Import Project="../WrathMod.props" />
	<ItemGroup>
		<ProjectReference Include="../WotRHomebrew.Logic/WotRHomebrew.Logic.csproj" />
		<ProjectReference Include="../WotRHomebrew.Core/WotRHomebrew.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="WotRHomebrew" />
	</ItemGroup>
</Project>
