<Project Sdk="Microsoft.NET.Sdk">
	<!-- Spell tags and spell-slot arcana. -->
	<Import Project="../WrathMod.props" />
	<ItemGroup>
		<ProjectReference Include="../ACHomebrew.Logic/ACHomebrew.Logic.csproj" />
		<ProjectReference Include="../ACHomebrew.Core/ACHomebrew.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="ACHomebrew" />
	</ItemGroup>
</Project>
